export interface Group {
    groupId: string,
    name: string,
    avatarUrl: string,
    createdAt: string,
    groupStatusName: string,
    groupStatusBackground: string,
    totalMembers: number,
    totalGlobalWallet: number,
    totalGlobalWalletPaid: number,
    currencyName: string,
    totalActivePolicies: number,
    totalOpenSinisters: number,
    createdByName: string,
    totalGlobalCurrentWallet: number,
    totalExpiredPolicies: number,
    totalCancelledPolicies: number,
}
