export interface Partner {
    partnerId: string,
    name: string,
    createdAt?: string,
    partnerStatusName?: string,
    partnerStatusBackground?: string,
    totalClients?: number,
    totalPolicies?: number,
    wallet?: number,
    walletPaid?: number,
    currencyName?: string,
    totalSinisters?: number,
    createdByName?: string,
    totalGlobalCurrentWallet?: number,
    totalActivePolicies?: number,
    totalExpiredPolicies?: number,
    totalCancelledPolicies?: number,
}
