export interface UpdateExternalPolicyDataSend {
    coveredProperty: string,
    policyNumber: string,
    clientNumber: string,
    insurerId: number,
    insuranceId: number,
    insuranceTypeId: number,
    titularName: string,
    titularRfc: string,
    titularPostalCode: string,
    titularPhoneNumber: string,
    emissionDate: string,
    validityStartDate: string,
    validityEndDate: string,
    netPay: string,
    feePay: string,
    coverPay: string,
    extraPay: string,
    taxPay: string,
    policyAmount: string,
    currencyId: number,
    paymentMethodId: number,
    paymentPlanId: number
}
