export interface Policy {
    policyId: string,
    insuranceId: number,
    insuranceName: string,
    insuranceIcon: string,
    insuranceBackground: string,
    insuranceTypeId: number,
    insuranceTypeName: string,
    policyStatusName: string,
    policyStatusDescription: string,
    policyStatusBackground: string,
    insurerId: number,
    insurerName: string,
    insurerImageUrl: string,
    amount: number,
    currencyName: string,
    paymentPlanName: string,
    policyNumber: string,
    policyUrl: string,
    coveredProperty: string,
    lifeTime: number,
    validityStartDate: string,
    validityEndDate: string
    policyStatusId: number
}
