export interface PolicyComplete {
    policyId: string,
    policyStatusName: string,
    policyStatusBackground: string,
    insuranceName: string,
    insuranceIcon: string,
    insuranceBackground: string,
    insuranceTypeName: string,
    policyUrl: string,
    coveredProperty: string,
    policyNumber: string,
    clientNumber: string,
    insurerName: string,
    titularName: string,
    titularRfc: string,
    titularPostalCode: string,
    titularPhoneNumber: string,
    emissionDate: string,
    validityStartDate: string,
    validityEndDate: string,
    amount: number,
    currencyName: string,
    paymentMethodName: string,
    paymentPlanName: string,
    bills: number
}
