export interface SinisterEvent {
    sinisterEventTypeId: number,
    evidenceName: string,
    providerName: string,
    providerDate: string,
    valuationDate: string,
    authorizationDate: string,
    insuredNoticeDate: string,
    insuredAuthorizationDate: string,
    estimatedDeliveryDate: string,
    repairDate: string,
    deliveryDate: string,
    readmissionDate: string,
    providerFolio: string,
    providerBill: string,
    providerPhoneCodeId: number,
    providerPhoneNumber: string,
    providerEmail: string,
    observations: string,
}
