export interface Sinister {
    sinisterId: number,
    sinisterNumber: string,
    invoice: string,
    certificate: string,
    sinisterDate: string,
    insurerImageUrl: string,
    sinisterStatusName: string,
    sinisterStatusBackground: string,
    sinisterStatusDescription: string,
    insuranceName: string,
    insuranceIcon: string,
    insuranceBackground: string,
    paymentPlanName: string,
    insuranceTypeName: string,
    coveredProperty: string,
    policyNumber: string,
    validityStartDate: string,
    validityEndDate: string,
    lifeTime: number,
    policyId: string,
    contactId: string,
    sinisterTypeName: string,
    totalEvents: number,
    titularName: string,
    dateLastEvent: string
}
