export interface UpdateContactDataSend {
    name: string,
    namePaternal: string,
    nameMaternal: string,
    genderId: number,
    birthdate: string,
    civilStatusId: number,
    contactOccupationId: number,
    offspringId: number,
    companyName: string,
    brandName: string,
    rfc: string,
    email: string,
    phoneCodeId: number,
    phoneNumber: string,
    website: string,
    street: string,
    exteriorNumber: string,
    interiorNumber: string,
    colony: string,
    city: string,
    state: string,
    postalCode: string,
    country: string,
    contactTypeId: number
}
