export interface Workspace {
    workspaceId: string,
    realName: string,
    brandName: string,
    avatarUrl: string,
    isActiveWorkspace: boolean,
    countryId: number,
    payLink: string,
    cardiumUrl: string,
    facebookUrl: string,
    instagramUrl: string,
    twitterUrl: string,
    linkedinUrl: string,
    tiktokUrl: string,
}
